#if defined __strings_struct_included
#endinput
#endif
#define __strings_struct_included

#undef STRING_SIZE
#define STRING_SIZE 2048
enum struct string
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 2
enum struct string_2
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 4
enum struct string_4
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 6
enum struct string_6
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 8
enum struct string_8
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 10
enum struct string_10
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 12
enum struct string_12
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 16
enum struct string_16
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 24
enum struct string_24
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 32
enum struct string_32
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 64
enum struct string_64
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 65
enum struct string_65
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 100
enum struct string_100
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 128
enum struct string_128
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 200
enum struct string_200
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 255
enum struct string_255
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 256
enum struct string_256
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 500
enum struct string_500
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 512
enum struct string_512
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 1000
enum struct string_1000
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 1024
enum struct string_1024
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 2000
enum struct string_2000
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 2048
enum struct string_2048
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 4000
enum struct string_4000
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 4096
enum struct string_4096
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 8000
enum struct string_8000
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 8192
enum struct string_8192
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 10000
enum struct string_10000
{
	#include "strings_include"
}
#undef STRING_SIZE
#define STRING_SIZE 10240
enum struct string_10240
{
	#include "strings_include"
}
